Issue2
romb-technologies/ariac_environment pull request #6
Opened 2019-04-02 16:38 UTC by filipkozlik

-added front and back laser sensor on top of pioneer robot
-position of sensors can be adjusted in /models/ariac/model.sdf
-sensor angle range can be adjusted in /models/custom_hokuyo/model-1_2.sdf

2019-04-03 22:52 UTC, dmiklic requested changes

2019-04-03 22:52 UTC, dmiklic commented on models/ariac/model.sdf
> +      <uri>model://custom_hokuyo</uri>
Seems like you have added the lasers directly into the world model, which seems unnatural. I suggest you create a new xacro model to describe the robot, which will include the pioneer xacro and the hokuyo xacro models.

2019-04-03 22:52 UTC, dmiklic commented on models/custom_hokuyo/model-1_4.sdf
> +<?xml version="1.0" ?>
Why do we have three different model files for the hokuyo, which seem to define very similar stuff?

2019-04-04 12:57 UTC, filipkozlik commented on models/ariac/model.sdf
> +      <uri>model://custom_hokuyo</uri>
I will change it to the way you specified.

2019-04-04 13:01 UTC, filipkozlik commented on models/custom_hokuyo/model-1_4.sdf
> +<?xml version="1.0" ?>
Those files were defined by hokuyo themselves to support different sdf versions. I will try to remove unnecessary files.

2019-04-04 13:18 UTC, dmiklic commented on models/custom_hokuyo/model-1_4.sdf
> +<?xml version="1.0" ?>
If this is the way the model is defined, it is not necessary that we change it.

2019-04-04 13:18 UTC, dmiklic commented on models/ariac/model.sdf
> +      <uri>model://custom_hokuyo</uri>
Cool, thanks!

2019-04-08 16:40 UTC, dmiklic requested changes

2019-04-08 16:40 UTC, dmiklic commented on launch/p3dx_in_ariac_world.launch
> +  <include file="$(find ariac_environment)/models/pioneer_sensor_model/launch/upload_pioneer3dx.xml"/>
All launch files should go into the top-level launch folder `ariac_environment/launch`

2019-04-08 16:40 UTC, dmiklic commented on models/hokuyo/hokuyo.xacro
> +<?xml version="1.0"?>
Please clean up indentation in the whole file. tabs should be 2 spaces.

2019-04-08 16:40 UTC, dmiklic commented on models/pioneer_sensor_model/defs/pioneer3dx.xacro
> +	<xacro:include filename="$(find ariac_environment)/models/pioneer_sensor_model/defs/pioneer3dx_body.xacro"/>
If `pioneer3dx_body.xacro` is identical to the one from the `p2os_urdf` package, we should just include that one.

2019-04-08 16:40 UTC, dmiklic commented on models/pioneer_sensor_model/defs/pioneer3dx.xacro
> +	<xacro:property name="laser_name" value="front_laser"/>
Pls fix indentation.

2019-04-08 16:40 UTC, dmiklic commented on models/pioneer_sensor_model/defs/pioneer3dx.xacro
> +	<xacro:property name="publish_topic" value="/pio_lasers/front_laser"/>
Value should be `"scan_front"`. Remove leading `/` it indicates an absolute path and paths should always be defined as relative to enable correct namespace scoping.

2019-04-08 16:40 UTC, dmiklic commented on models/pioneer_sensor_model/defs/pioneer3dx.xacro
> +	<xacro:property name="publish_topic" value="/pio_lasers/back_laser"/>
Value should be `"scan_back"`, same rationale as above.

2019-04-08 16:40 UTC, dmiklic commented on models/pioneer_sensor_model/defs/pioneer3dx_body.xacro
> +<?xml version="1.0"?>
if this file is identical to the one in `p2os_urdf`, we should delete it and use that one.

2019-04-08 16:40 UTC, dmiklic commented on models/pioneer_sensor_model/launch/upload_pioneer3dx.xml
> +<launch>
Move launch file to top-level launch folder.

2019-04-08 16:40 UTC, dmiklic commented on models/pioneer_sensor_model/defs/pioneer3dx.xacro
> +<?xml version="1.0"?>
Rename folder to `p3dx_with_sensors`

2019-04-08 17:16 UTC, filipkozlik commented on models/pioneer_sensor_model/defs/pioneer3dx.xacro
> +	<xacro:property name="publish_topic" value="/pio_lasers/front_laser"/>
Should it just be "scan_front" or should I add something in front of it (e.g. "pioneer/scan_front")?

2019-04-08 17:18 UTC, dmiklic commented on models/pioneer_sensor_model/defs/pioneer3dx.xacro
> +	<xacro:property name="publish_topic" value="/pio_lasers/front_laser"/>
Just scan_front. The prefix can be added at runtime by namespacing or topic renaming.

2019-04-08 17:47 UTC, merged